# Generated by Django 6.0 on 2025-12-17 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('weight', models.FloatField(help_text='Toplam ağırlık (kg)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargoes', to='api.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
