# Generated by Django 6.0 on 2025-12-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_weight', models.FloatField(help_text='Araç başına maksimum taşıma kapasitesi (kg)')),
                ('is_rented', models.BooleanField(default=False, help_text='Kiralık mı?')),
                ('rental_cost', models.FloatField(default=0, help_text='Araç kiralama maliyeti')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
