# Generated by Django 6.0 on 2025-12-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cargoassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
