# Generated by Django 6.0 on 2025-12-20 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cargoassignment_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem_type', models.CharField(choices=[('fixed', 'Sabit Araç'), ('unlimited', 'Sınırsız Araç')], max_length=20)),
                ('vehicles_used', models.PositiveIntegerField()),
                ('total_distance', models.FloatField(help_text='Toplam mesafe (km)')),
                ('total_weight', models.FloatField(help_text='Toplam taşınan ağırlık (kg)')),
                ('total_cost', models.FloatField(help_text='Toplam maliyet')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cargoassignment',
            name='optimization_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.optimizationrun'),
        ),
    ]
