# Generated by Django 6.0 on 2025-12-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_optimizationrun_cargoassignment_optimization_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationrun',
            name='route',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
