# Generated by Django 6.0 on 2025-12-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_optimizationrun_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stations', models.JSONField()),
                ('path', models.JSONField()),
                ('total_distance', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('optimization_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_routes', to='api.optimizationrun')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.vehicle')),
            ],
        ),
    ]
