# Generated by Django 6.0 on 2025-12-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_vehicleroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoassignment',
            name='loaded_weight',
            field=models.FloatField(default=0),
        ),
    ]
